U4X-521:Refactoring code to enable the launch of TB and HIV enrolment…
METS-Programme/openmrs-module-ugandaemr pull request #474
Opened 2024-04-04 13:03 UTC by Mwanje

https://metsprogramme.atlassian.net/browse/U4X-521

2024-04-04 14:01 UTC, akileng56 requested changes

2024-04-04 14:01 UTC, akileng56 commented on api/src/main/java/org/openmrs/module/ugandaemr/UgandaEMRConstants.java
> +    public static final String HIV_ENROLLMENT_FORM_NAME ="HMIS ACP HIV 003: HIV CARE/ART CARD - Summary Form";
Musa doesn't this make us have two forms of the summary Form

2024-04-07 04:55 UTC, slubwama requested changes

2024-04-07 04:55 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemr/UgandaEMRConstants.java
> +    public static final String DS_TB_ENROLLMENT_FORM_UUID ="f5e06c9a-0468-337f-b1b4-d5239cb5dbc6";
the actual form uuid for the DS enrollment form is  "b00452b6-bb7c-11ea-b3de-0242ac130004"

2024-04-07 04:55 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemr/UgandaEMRConstants.java
> +    public static final String HIV_ENROLLMENT_FORM_UUID ="2efbb08f-e6df-3791-bbd7-8de42eeb9cd7";
The actual form uuif form the HIV Enrollment form is 52653a60-8300-4c13-be4d-4b746da06fee

2024-04-16 15:40 UTC, slubwama approved these changes

2024-04-16 15:41 UTC, slubwama approved these changes

2024-04-16 16:00 UTC, akileng56 approved these changes

2024-04-16 16:01 UTC, merged