U4X-686: Refactor HMIS ACP 018:HTS Client Card
METS-Programme/openmrs-module-ugandaemr pull request #620
Opened 2024-10-18 06:33 UTC by Daphne210

https://metsprogramme.atlassian.net/browse/U4X-675

2025-02-15 05:29 UTC, slubwama commented
@Mwanje  46648b1d-b099-433b-8f9c-3815ff1e0a0f used on  both HTS models and  mg/m2 create new concept for HTS models and move all related concept to in

2025-02-15 11:07 UTC, slubwama requested changes
Concept 164989 on testing for the first time is wrong change to

Remove location where tested since its no longer required

2025-02-15 11:07 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-018-HTSClientCard.json
> +                    "label": "Family Planning Services",
use 5271 instead of 164984AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

2025-02-15 11:07 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-018-HTSClientCard.json
> +                    "concept": "11c12455-2f54-4bb5-b051-0ecfd4a5fe96",
use 5484 instead of 11c12455-2f54-4bb5-b051-0ecfd4a5fe96

2025-02-15 11:07 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-018-HTSClientCard.json
> +                    "concept": "160456AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
use 166940 instead. 160456AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

2025-02-15 11:07 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-018-HTSClientCard.json
> +                    "concept": "165046AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
use 166939 instead of 165046AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

2025-02-15 11:07 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-018-HTSClientCard.json
> +                    "label": "EID",
use 99087

2025-02-15 11:07 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-018-HTSClientCard.json
> +                    "label": "AYP",
use YAPS

2025-02-15 11:07 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-018-HTSClientCard.json
> +              "label": "Testing for HIV for the first time",
concept  used "164989AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" is for HIVDR Sample Collected not Testing for HIV for the first time. Instead use (165180)

2025-02-15 11:07 UTC, slubwama commented
@Daphne210  see comments on PR

2025-02-17 07:32 UTC, Daphne210 commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-018-HTSClientCard.json
> +                    "concept": "160456AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
This has been changed

2025-02-17 07:33 UTC, Daphne210 commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-018-HTSClientCard.json
> +                    "concept": "165046AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
This has been changed.

2025-02-17 07:33 UTC, Daphne210 commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-018-HTSClientCard.json
> +                    "label": "Family Planning Services",
This has been changed.

2025-02-17 07:34 UTC, Daphne210 commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-018-HTSClientCard.json
> +                    "concept": "11c12455-2f54-4bb5-b051-0ecfd4a5fe96",
This has been changed.

2025-02-17 07:36 UTC, Daphne210 commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-018-HTSClientCard.json
> +                    "label": "AYP",
This has been changed.

2025-02-17 07:37 UTC, Daphne210 commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-018-HTSClientCard.json
> +              "label": "Testing for HIV for the first time",
This has been changed.

2025-02-21 07:49 UTC, slubwama approved these changes

2025-02-21 07:49 UTC, merged