U4X-681: Add HIV Self Test Form
METS-Programme/openmrs-module-ugandaemr pull request #623
Opened 2024-10-18 06:51 UTC by Daphne210

https://metsprogramme.atlassian.net/browse/U4X-681

2024-10-19 11:49 UTC, slubwama requested changes

2024-10-19 11:49 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-008-ComprehensiveARTPatientTransferOutForm.json
@Daphne210  Why Delete the Comprehensive HIV Care/ART Patient Transfer Out Form

2024-10-19 12:27 UTC, Daphne210 commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-008-ComprehensiveARTPatientTransferOutForm.json
It wasn't merged in at the time of pushing the PR but I had it on my local I will pull the latest master when working on it to include it

2025-05-21 23:49 UTC, Daphne210 commented
Not to do

2025-05-21 23:49 UTC, closed without merging