Add new Physco-social form
METS-Programme/openmrs-module-ugandaemr pull request #644
Opened 2024-10-22 11:31 UTC by jabahum

- HMIS 2024

2024-10-22 12:24 UTC, akileng56 requested changes

2024-10-22 12:24 UTC, akileng56 commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-003-HIVART-CARD - HEALTH EDUCATION AND PSYCHOSOCIAL SUPPORT PAGE v2.json
> +  "encounterType": "e22e39fd-7db2-45e7-80f1-60fa0d5a4378",
`6d88e370-f2ba-476b-bf1b-d8eaf3b1b67e` Use the same as the xml form

2024-10-22 12:24 UTC, akileng56 commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-003-HIVART-CARD - HEALTH EDUCATION AND PSYCHOSOCIAL SUPPORT PAGE v2.json
> +  "uuid": "26687e48-c7ea-4ca7-b878-e90b742b01f5",
`b8224534-7df0-4c00-ba8e-6b1f291087eb` Same here, Wrong uuid used

2024-10-22 12:34 UTC, akileng56 commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-003-HIVART-CARD - HEALTH EDUCATION AND PSYCHOSOCIAL SUPPORT PAGE v2.json
> +  "name": "HMIS ACP 003 : HIV CARE/ART CARD - HEALTH EDUCATION AND PSYCHOSOCIAL SUPPORT PAGE v2",
What does `PAGE v2` mean?

2024-10-22 12:35 UTC, akileng56 commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-003-HIVART-CARD - HEALTH EDUCATION AND PSYCHOSOCIAL SUPPORT PAGE v2.json
> +  "pages": [
We need to stick to a standard `Pages` Vs `Sections`

2024-10-22 14:07 UTC, Mwanje commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-003-HIVART-CARD - HEALTH EDUCATION AND PSYCHOSOCIAL SUPPORT PAGE v2.json
> +      "label": "Name of Service Provider",
@jabahum lets remove this section

2024-10-22 16:31 UTC, jabahum commented on omod/src/main/webapp/resources/jsonforms/HMIS-ACP-003-HIVART-CARD - HEALTH EDUCATION AND PSYCHOSOCIAL SUPPORT PAGE v2.json
> +  "pages": [
at the beginning its always pages

2024-10-23 07:28 UTC, slubwama commented
@jabahum make sure your changes are overwrite the existing file. In this file I see  v2 additives. Lets change that.

2024-10-23 11:19 UTC, jabahum commented
Noted

2025-02-21 07:50 UTC, closed without merging