U4X-753: Refactor HMIS ACP HIV 003: HIV CARE/ART CARD - Summary Form
METS-Programme/openmrs-module-ugandaemr pull request #684
Opened 2024-12-09 18:34 UTC by Daphne210

https://metsprogramme.atlassian.net/browse/U4X-753

2025-02-09 02:17 UTC, slubwama requested changes

2025-02-09 02:17 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/003-HMIS_ACP_ARTCard-SummaryPage .json
>                  "concept": "dcdfe3ce-30ab-102d-86b0-7a5022ba4115",
Change to 7b082783-658c-4867-a650-ba5bdfa65d53 (Out Reach activity) The current one reads IUD Reachout

2025-02-09 02:17 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/003-HMIS_ACP_ARTCard-SummaryPage .json
> +        {
Wrap this in a grouping Obs Called Baseline eMTCT

2025-02-11 18:14 UTC, Daphne210 commented on omod/src/main/webapp/resources/jsonforms/003-HMIS_ACP_ARTCard-SummaryPage .json
> +        {
@slubwama cannot find such concept named baseline emtct

2025-02-11 18:49 UTC, Daphne210 commented on omod/src/main/webapp/resources/jsonforms/003-HMIS_ACP_ARTCard-SummaryPage .json
>                  "concept": "dcdfe3ce-30ab-102d-86b0-7a5022ba4115",
This has been resolved.

2025-02-13 17:34 UTC, Daphne210 commented on omod/src/main/webapp/resources/jsonforms/003-HMIS_ACP_ARTCard-SummaryPage .json
> +        {
This has been resolved.

2025-02-14 12:03 UTC, slubwama requested changes

2025-02-14 12:03 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/003-HMIS_ACP_ARTCard-SummaryPage .json
> +                "concept": "33b18e88-0eb9-48f0-8023-2e90caad4469",
Concept used for relationship is concept for age. Instead use 
bc61e60a-53ce-4767-8eed-29f3ec088829

2025-02-14 12:03 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/003-HMIS_ACP_ARTCard-SummaryPage .json
> +                "concept": "33b18e88-0eb9-48f0-8023-2e90caad4469",
@Mwanje  add this (99120) "bc61e60a-53ce-4767-8eed-29f3ec088829" concept to set  (90289) dd23fbee-30ab-102d-86b0-7a5022ba4115

2025-02-14 12:03 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/003-HMIS_ACP_ARTCard-SummaryPage .json
> +                    "label": "Partner"
Is this partner or parent. Concept used reads Parent

2025-02-14 12:03 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/003-HMIS_ACP_ARTCard-SummaryPage .json
> +                "concept": "dce17480-30ab-102d-86b0-7a5022ba4115"
@Mwanje add concept (90278) dce17480-30ab-102d-86b0-7a5022ba4115 to set (90289) dd23fbee-30ab-102d-86b0-7a5022ba4115

2025-02-14 12:03 UTC, slubwama commented on omod/src/main/webapp/resources/jsonforms/003-HMIS_ACP_ARTCard-SummaryPage .json
> +          "label": "eMTCT Status",
This should be part of the baseline section and concept to use is (199088) f838147d-277d-421a-9c6f-202aa30e799c

2025-02-17 08:33 UTC, slubwama approved these changes

2025-02-17 08:33 UTC, merged